os: linux
sudo: false
language: go
cache: pip

matrix:
  include:
    - go: "1.10.1"
    - go: master
  fast_finish: true

services: postgresql

install:
  - true

script:
  - go test -v ./...

notifications:
  email: false
